baseURL = 'https://ahsanujunda.github.io/'
languageCode = 'en-us'
title = 'Izzuddin Ahsanujunda'
theme = "PaperMod"

[params]
  author = "Junda"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archives"
    weight = 5
  [[menu.main]]
    name = "Search"
    url = "/search"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 15

[permalinks]
  posts = "/:year/:month/:day/:slug/"  # match your existing Hexo URLs