baseURL = 'https://ahsanujunda.github.io/'
languageCode = 'en-us'
title = 'Izzuddin Ahsanujunda'
theme = "PaperMod"

[params]
  author = "Junda"
  
  [params.homeInfoParams]
  Title = "Learned Something, write  down!"
  Content = "Find me on"

  [[params.socialIcons]]
  name = "github"
  url = "github.com/iahsanujunda"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archives"
    weight = 5
  [[menu.main]]
    name = "Search"
    url = "/search"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 15

[permalinks]
  posts = "/:year/:month/:day/:slug/"  # match your existing Hexo URLs

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
