projects:
- name: iahsanujunda.me
  environments:
  - name: Production
    services:
    - type: web
      runtime: static
      name: iahsanujunda-hugo
      buildCommand: |
        curl -sSL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz" | tar -xz hugo
        ./hugo --minify
      staticPublishPath: public
      pullRequestPreviewsEnabled: false
      envVars:
      - key: HUGO_VERSION
        value: 0.146.0
      domains:
      - iahsanujunda.me
      - www.iahsanujunda.me