projects:
- name: iahsanujunda.me
  environments:
  - name: Production
    services:
    - type: web
      runtime: static
      name: iahsanujunda-hugo
      buildCommand: hugo --minify
      staticPublishPath: public
      pullRequestPreviewsEnabled: false
      envVars:
      - key: HUGO_VERSION
        value: 0.146.0
      domains:
      - iahsanujunda.me
      - www.iahsanujunda.me