projects:
- name: iahsanujunda.me
  environments:
  - name: Production
    services:
    - type: web
      runtime: static
      name: iahsanujunda-hugo
      buildCommand: hugo --minify
      staticPublishPath: public
      pullRequestPreviewsEnabled: false
      domains:
      - iahsanujunda.me
      - www.iahsanujunda.me